#pragma once

// ============================== Базовые шейдеры (без текстуры) ==============================

static const char* SHADER_BASIC_VS =
"#version 330 core\n"
"layout(location = 0) in vec3 aPos;\n"
"layout(location = 1) in vec3 aNormal;\n"
"layout(location = 2) in vec2 aUV;\n"
"\n"
"uniform mat4 uModel;\n"
"uniform mat4 uViewProj;\n"
"\n"
"out vec3 vWorldPos;\n"
"out vec3 vNormal;\n"
"out vec2 vUV;\n"
"\n"
"void main() {\n"
"    vec4 world = uModel * vec4(aPos, 1.0);\n"
"    vWorldPos = world.xyz;\n"
"    vNormal = mat3(uModel) * aNormal;\n"
"    vUV = aUV;\n"
"    gl_Position = uViewProj * world;\n"
"}\n";

static const char* SHADER_BASIC_FS =
"#version 330 core\n"
"in vec3 vWorldPos;\n"
"in vec3 vNormal;\n"
"in vec2 vUV;\n"
"\n"
"uniform vec3 uAmbient;\n"
"uniform vec3 uDirLightDir;\n"
"uniform vec3 uDirLightColor;\n"
"uniform float uDirLightIntensity;\n"
"uniform sampler2D uTexture;\n"
"uniform int uUseTexture;\n"
"uniform vec3 uFlatColor;\n"
"\n"
"out vec4 FragColor;\n"
"\n"
"void main() {\n"
"    vec3 N = normalize(vNormal);\n"
"    vec3 L = normalize(-uDirLightDir);\n"
"    float ndl = max(dot(N, L), 0.0);\n"
"    vec3 light = uAmbient + uDirLightColor * uDirLightIntensity * ndl;\n"
"\n"
"    vec3 baseColor;\n"
"    if (uUseTexture != 0) {\n"
"        baseColor = texture(uTexture, vUV).rgb;\n"
"    } else {\n"
"        baseColor = uFlatColor;\n"
"    }\n"
"    FragColor = vec4(baseColor * light, 1.0);\n"
"}\n";